server:
  port: 10001
  servlet:
    context-path: /railgun


#spring:
#  resources:
#    static-locations:
#      - classpath:/railgun1/
#      - classpath:/railgun2/
#      - classpath:/
spring:
  mvc:
    date-format: dd-MM-yyyy
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login