server:
  port: 10000

spring:
  application:
    name: 6.zuul

# 注册中心配置
eureka:
  client:
    service-url:
      #defaultZone: http://railgun.com:7000/eureka/,http://railgun1.com:7001/eureka/,http://railgun2.com:7002/eureka/
      defaultZone: http://railgun.com:7000/eureka/
    # 不向 Eureka 中注册自己【测试需要，所以将配置注释掉】
    #register-with-eureka: false
  instance:
    instance-id: zuul
    # Eureka 注册中心应用名称
    appname: 6.zuul
    # 显示 ip
    prefer-ip-address: true
info:
  app.name: railgun-zuul
  company.name: raigun.com

zuul:
  routes:
    mydept.serviceId: 3.consumer-dept-80
    mydept.path: /mydept/**
  #  隐藏全部的微服务名称
  ignored-services: "*"
  # 访问的时候统一的前缀
  prefix: /railgun